package com.wordguessing.game

object WordBank {

    val categories = mapOf(

        "Animals" to listOf(
            "ELEPHANT",
            "TIGER",
            "LION",
            "GIRAFFE",
            "KANGAROO",
            "PENGUIN",
            "DOLPHIN",
            "CROCODILE",
            "ALLIGATOR",
            "MONKEY",
            "GORILLA",
            "CHEETAH",
            "LEOPARD",
            "WOLF",
            "FOX",
            "BEAR",
            "RABBIT",
            "SQUIRREL",
            "DEER",
            "CAMEL",
            "HORSE",
            "DONKEY",
            "ZEBRA",
            "GOAT",
            "SHEEP",
            "COW",
            "BUFFALO",
            "CHICKEN",
            "ROOSTER",
            "EAGLE",
            "HAWK",
            "PARROT",
            "OWL",
            "FLAMINGO",
            "PEACOCK",
            "OSTRICH",
            "OCTOPUS",
            "SQUID",
            "SHARK",
            "WHALE",
            "SEAL",
            "WALRUS",
            "TURTLE",
            "SNAKE",
            "LIZARD",
            "FROG",
            "BUTTERFLY",
            "SPIDER"
        ),

        "Food" to listOf(
            "PIZZA",
            "BURGER",
            "SANDWICH",
            "PANCAKES",
            "WAFFLES",
            "SPAGHETTI",
            "LASAGNA",
            "TACOS",
            "BURRITO",
            "NACHOS",
            "HOT DOG",
            "FRENCH FRIES",
            "CHICKEN NUGGETS",
            "FRIED CHICKEN",
            "GRILLED CHEESE",
            "MACARONI",
            "CHEESECAKE",
            "ICE CREAM",
            "CHOCOLATE",
            "DONUT",
            "CUPCAKE",
            "BROWNIE",
            "COOKIE",
            "APPLE PIE",
            "PUMPKIN PIE",
            "WATERMELON",
            "STRAWBERRY",
            "BLUEBERRY",
            "PINEAPPLE",
            "MANGO",
            "BANANA",
            "ORANGE",
            "GRAPES",
            "POTATO",
            "CARROT",
            "BROCCOLI",
            "SPINACH",
            "CORN",
            "TOMATO",
            "CUCUMBER",
            "POPCORN",
            "PRETZEL",
            "PEANUT BUTTER",
            "HONEY",
            "YOGURT",
            "CHEESE",
            "RICE",
            "NOODLES",
            "CHOCOLATE CAKE",
            "FRUIT SALAD"
        ),

        "Places" to listOf(
            "NEW YORK",
            "LOS ANGELES",
            "CHICAGO",
            "MIAMI",
            "BOSTON",
            "SEATTLE",
            "DALLAS",
            "HOUSTON",
            "LAS VEGAS",
            "SAN FRANCISCO",
            "WASHINGTON DC",
            "NEW ORLEANS",
            "ORLANDO",
            "DENVER",
            "PHOENIX",
            "ATLANTA",
            "LONDON",
            "PARIS",
            "ROME",
            "MADRID",
            "BERLIN",
            "DUBAI",
            "ISTANBUL",
            "CAIRO",
            "TOKYO",
            "SEOUL",
            "BEIJING",
            "MUMBAI",
            "DELHI",
            "SYDNEY",
            "TORONTO",
            "VANCOUVER",
            "MEXICO CITY",
            "NIAGARA FALLS",
            "GRAND CANYON",
            "YELLOWSTONE",
            "DISNEY WORLD",
            "TIMES SQUARE",
            "CENTRAL PARK",
            "GOLDEN GATE BRIDGE",
            "STATUE OF LIBERTY",
            "WHITE HOUSE",
            "EIFFEL TOWER",
            "BIG BEN",
            "TAJ MAHAL",
            "GREAT WALL",
            "MOUNT EVEREST",
            "NILE RIVER",
            "ATLANTIC OCEAN",
            "PACIFIC OCEAN"
        ),

        "Sports" to listOf(
            "SOCCER",
            "FOOTBALL",
            "BASKETBALL",
            "BASEBALL",
            "CRICKET",
            "TENNIS",
            "GOLF",
            "HOCKEY",
            "VOLLEYBALL",
            "SWIMMING",
            "BOXING",
            "WRESTLING",
            "WRESTLING MATCH",
            "TABLE TENNIS",
            "BADMINTON",
            "BOWLING",
            "SKIING",
            "SNOWBOARDING",
            "SURFING",
            "CYCLING",
            "RUNNING",
            "MARATHON",
            "FORMULA ONE",
            "CAR RACING",
            "HORSE RACING",
            "ARCHERY",
            "GYMNASTICS",
            "FIGURE SKATING",
            "ICE SKATING",
            "WATER POLO",
            "BEACH VOLLEYBALL",
            "AMERICAN FOOTBALL",
            "TOUCHDOWN",
            "HOME RUN",
            "FREE THROW",
            "THREE POINTER",
            "PENALTY KICK",
            "RED CARD",
            "YELLOW CARD",
            "WORLD CUP",
            "SUPER BOWL",
            "OLYMPIC GAMES",
            "CHAMPIONSHIP",
            "REFEREE",
            "GOALKEEPER",
            "QUARTERBACK",
            "PITCHER",
            "BATSMAN",
            "TEAM CAPTAIN"
        ),

        "Movies" to listOf(
            "THE LION KING",
            "TOY STORY",
            "FINDING NEMO",
            "FINDING DORY",
            "SHREK",
            "FROZEN",
            "MOANA",
            "ALADDIN",
            "MULAN",
            "CINDERELLA",
            "THE JUNGLE BOOK",
            "BEAUTY AND THE BEAST",
            "THE INCREDIBLES",
            "MONSTERS INC",
            "CARS",
            "RATATOUILLE",
            "UP",
            "WALL E",
            "COCO",
            "ENCANTO",
            "HOME ALONE",
            "THE MATRIX",
            "JURASSIC PARK",
            "STAR WARS",
            "STAR TREK",
            "SPIDER MAN",
            "BATMAN",
            "SUPERMAN",
            "IRON MAN",
            "BLACK PANTHER",
            "THE AVENGERS",
            "GUARDIANS OF THE GALAXY",
            "HARRY POTTER",
            "THE HOBBIT",
            "LORD OF THE RINGS",
            "PIRATES OF THE CARIBBEAN",
            "MISSION IMPOSSIBLE",
            "TOP GUN",
            "ROCKY",
            "KARATE KID",
            "BACK TO THE FUTURE",
            "JUMANJI",
            "MEN IN BLACK",
            "GHOSTBUSTERS",
            "GODZILLA",
            "KING KONG",
            "SPACE JAM",
            "HOME ALONE 2",
            "THE MASK",
            "THE TERMINATOR"
        ),

        "Things" to listOf(
            "TELEPHONE",
            "COMPUTER",
            "LAPTOP",
            "KEYBOARD",
            "TELEVISION",
            "CAMERA",
            "HEADPHONES",
            "MICROWAVE",
            "REFRIGERATOR",
            "TOASTER",
            "VACUUM CLEANER",
            "WASHING MACHINE",
            "DISHWASHER",
            "UMBRELLA",
            "BACKPACK",
            "SUITCASE",
            "WALLET",
            "WATCH",
            "SUNGLASSES",
            "BICYCLE",
            "SKATEBOARD",
            "BALL",
            "GUITAR",
            "PIANO",
            "DRUM",
            "BOOK",
            "PENCIL",
            "NOTEBOOK",
            "SCISSORS",
            "HAMMER",
            "SCREWDRIVER",
            "LADDER",
            "FLASHLIGHT",
            "CANDLE",
            "PILLOW",
            "BLANKET",
            "CHAIR",
            "TABLE",
            "SOFA",
            "BED",
            "MIRROR",
            "TOOTHBRUSH",
            "WATER BOTTLE",
            "COFFEE CUP",
            "KEYCHAIN",
            "DOOR",
            "WINDOW",
            "CLOCK",
            "TELESCOPE"
        )
    )
}
